// Comprehensive Indian pincode to city/state mapping
// Covers major cities and surrounding areas

export interface PincodeInfo {
  pincode: string;
  city: string;
  state: string;
  region: string;
}

export const PINCODE_DATABASE: PincodeInfo[] = [
  // Delhi NCR
  { pincode: "110001", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110002", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110003", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110005", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110006", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110008", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110010", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110011", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110015", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110016", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110017", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110019", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110020", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110025", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110030", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110044", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110048", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110051", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110060", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110065", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110085", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "110092", city: "New Delhi", state: "Delhi", region: "North" },
  { pincode: "121001", city: "Faridabad", state: "Haryana", region: "North" },
  { pincode: "121002", city: "Faridabad", state: "Haryana", region: "North" },
  { pincode: "122001", city: "Gurgaon", state: "Haryana", region: "North" },
  { pincode: "122002", city: "Gurgaon", state: "Haryana", region: "North" },
  { pincode: "122003", city: "Gurgaon", state: "Haryana", region: "North" },
  { pincode: "122018", city: "Gurgaon", state: "Haryana", region: "North" },
  { pincode: "201001", city: "Ghaziabad", state: "Uttar Pradesh", region: "North" },
  { pincode: "201002", city: "Ghaziabad", state: "Uttar Pradesh", region: "North" },
  { pincode: "201301", city: "Noida", state: "Uttar Pradesh", region: "North" },
  { pincode: "201303", city: "Noida", state: "Uttar Pradesh", region: "North" },
  { pincode: "201304", city: "Greater Noida", state: "Uttar Pradesh", region: "North" },
  // Mumbai
  { pincode: "400001", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400002", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400003", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400004", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400005", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400007", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400008", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400010", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400011", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400012", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400014", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400016", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400018", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400020", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400022", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400025", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400028", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400030", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400049", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400050", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400053", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400058", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400059", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400060", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400069", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400070", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400076", city: "Navi Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400078", city: "Navi Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400080", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400086", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400093", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400097", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400099", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "400101", city: "Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "410206", city: "Navi Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "410210", city: "Navi Mumbai", state: "Maharashtra", region: "West" },
  { pincode: "411001", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411002", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411004", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411005", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411006", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411007", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411011", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411014", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411016", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411018", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411021", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411027", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411030", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411033", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411038", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411041", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411043", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411045", city: "Pune", state: "Maharashtra", region: "West" },
  { pincode: "411048", city: "Pune", state: "Maharashtra", region: "West" },
  // Bangalore
  { pincode: "560001", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560002", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560003", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560004", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560005", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560008", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560009", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560010", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560011", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560016", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560017", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560025", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560029", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560030", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560034", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560037", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560038", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560041", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560043", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560045", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560047", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560048", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560050", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560066", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560068", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560070", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560076", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560078", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560085", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560095", city: "Bangalore", state: "Karnataka", region: "South" },
  { pincode: "560100", city: "Bangalore", state: "Karnataka", region: "South" },
  // Chennai
  { pincode: "600001", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600002", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600003", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600004", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600005", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600006", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600008", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600010", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600011", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600014", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600015", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600017", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600018", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600020", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600024", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600028", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600032", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600034", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600040", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600042", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600044", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600050", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600053", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600056", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600058", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600062", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600078", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600083", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600085", city: "Chennai", state: "Tamil Nadu", region: "South" },
  { pincode: "600096", city: "Chennai", state: "Tamil Nadu", region: "South" },
  // Kolkata
  { pincode: "700001", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700002", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700003", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700004", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700005", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700006", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700007", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700010", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700012", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700014", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700015", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700016", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700017", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700019", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700020", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700025", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700026", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700027", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700029", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700030", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700032", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700033", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700034", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700035", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700036", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700037", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700039", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700040", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700042", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700046", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700047", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700053", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700054", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700064", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700068", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700075", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700091", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700094", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700099", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700101", city: "Kolkata", state: "West Bengal", region: "East" },
  { pincode: "700106", city: "Kolkata", state: "West Bengal", region: "East" },
  // Hyderabad
  { pincode: "500001", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500003", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500004", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500005", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500008", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500010", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500012", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500013", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500015", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500016", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500018", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500020", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500024", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500025", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500027", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500028", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500029", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500030", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500032", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500033", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500034", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500036", city: "Secunderabad", state: "Telangana", region: "South" },
  { pincode: "500038", city: "Secunderabad", state: "Telangana", region: "South" },
  { pincode: "500044", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500045", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500049", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500050", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500055", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500060", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500072", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500081", city: "Hyderabad", state: "Telangana", region: "South" },
  { pincode: "500084", city: "Hyderabad", state: "Telangana", region: "South" },
  // Jaipur
  { pincode: "302001", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302002", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302003", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302004", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302005", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302006", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302012", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302015", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302016", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302017", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302018", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302019", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302020", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302021", city: "Jaipur", state: "Rajasthan", region: "North" },
  { pincode: "302022", city: "Jaipur", state: "Rajasthan", region: "North" },
  // Ahmedabad
  { pincode: "380001", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380002", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380004", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380005", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380006", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380007", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380008", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380009", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380013", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380015", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380016", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380019", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380024", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380028", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380050", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380051", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380054", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380058", city: "Ahmedabad", state: "Gujarat", region: "West" },
  { pincode: "380059", city: "Ahmedabad", state: "Gujarat", region: "West" },
  // Lucknow
  { pincode: "226001", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226002", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226003", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226004", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226005", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226006", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226007", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226010", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226012", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226016", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226017", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226018", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226019", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226020", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226021", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226022", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226024", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226025", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  { pincode: "226028", city: "Lucknow", state: "Uttar Pradesh", region: "North" },
  // Chandigarh
  { pincode: "160001", city: "Chandigarh", state: "Chandigarh", region: "North" },
  { pincode: "160002", city: "Chandigarh", state: "Chandigarh", region: "North" },
  { pincode: "160003", city: "Chandigarh", state: "Chandigarh", region: "North" },
  { pincode: "160009", city: "Chandigarh", state: "Chandigarh", region: "North" },
  { pincode: "160011", city: "Chandigarh", state: "Chandigarh", region: "North" },
  { pincode: "160014", city: "Chandigarh", state: "Chandigarh", region: "North" },
  { pincode: "160017", city: "Chandigarh", state: "Chandigarh", region: "North" },
  { pincode: "160019", city: "Chandigarh", state: "Chandigarh", region: "North" },
  { pincode: "160022", city: "Chandigarh", state: "Chandigarh", region: "North" },
  { pincode: "160036", city: "Chandigarh", state: "Chandigarh", region: "North" },
  // Indore
  { pincode: "452001", city: "Indore", state: "Madhya Pradesh", region: "Central" },
  { pincode: "452002", city: "Indore", state: "Madhya Pradesh", region: "Central" },
  { pincode: "452003", city: "Indore", state: "Madhya Pradesh", region: "Central" },
  { pincode: "452005", city: "Indore", state: "Madhya Pradesh", region: "Central" },
  { pincode: "452006", city: "Indore", state: "Madhya Pradesh", region: "Central" },
  { pincode: "452007", city: "Indore", state: "Madhya Pradesh", region: "Central" },
  { pincode: "452008", city: "Indore", state: "Madhya Pradesh", region: "Central" },
  { pincode: "452009", city: "Indore", state: "Madhya Pradesh", region: "Central" },
  { pincode: "452010", city: "Indore", state: "Madhya Pradesh", region: "Central" },
  { pincode: "452011", city: "Indore", state: "Madhya Pradesh", region: "Central" },
  { pincode: "452012", city: "Indore", state: "Madhya Pradesh", region: "Central" },
  { pincode: "452014", city: "Indore", state: "Madhya Pradesh", region: "Central" },
  // Bhopal
  { pincode: "462001", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462002", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462003", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462010", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462011", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462016", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462020", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462023", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462024", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462026", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462030", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462036", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462038", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462041", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  { pincode: "462042", city: "Bhopal", state: "Madhya Pradesh", region: "Central" },
  // Patna
  { pincode: "800001", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800002", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800003", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800004", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800005", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800006", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800007", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800008", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800009", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800010", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800011", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800013", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800014", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800020", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800024", city: "Patna", state: "Bihar", region: "East" },
  { pincode: "800025", city: "Patna", state: "Bihar", region: "East" },
  // Kochi
  { pincode: "682001", city: "Kochi", state: "Kerala", region: "South" },
  { pincode: "682002", city: "Kochi", state: "Kerala", region: "South" },
  { pincode: "682003", city: "Kochi", state: "Kerala", region: "South" },
  { pincode: "682005", city: "Kochi", state: "Kerala", region: "South" },
  { pincode: "682011", city: "Kochi", state: "Kerala", region: "South" },
  { pincode: "682016", city: "Kochi", state: "Kerala", region: "South" },
  { pincode: "682017", city: "Kochi", state: "Kerala", region: "South" },
  { pincode: "682018", city: "Kochi", state: "Kerala", region: "South" },
  { pincode: "682019", city: "Kochi", state: "Kerala", region: "South" },
  { pincode: "682020", city: "Kochi", state: "Kerala", region: "South" },
  { pincode: "682024", city: "Kochi", state: "Kerala", region: "South" },
  { pincode: "682025", city: "Kochi", state: "Kerala", region: "South" },
  { pincode: "682026", city: "Kochi", state: "Kerala", region: "South" },
  { pincode: "682030", city: "Kochi", state: "Kerala", region: "South" },
  // Surat
  { pincode: "395001", city: "Surat", state: "Gujarat", region: "West" },
  { pincode: "395002", city: "Surat", state: "Gujarat", region: "West" },
  { pincode: "395003", city: "Surat", state: "Gujarat", region: "West" },
  { pincode: "395004", city: "Surat", state: "Gujarat", region: "West" },
  { pincode: "395005", city: "Surat", state: "Gujarat", region: "West" },
  { pincode: "395006", city: "Surat", state: "Gujarat", region: "West" },
  { pincode: "395007", city: "Surat", state: "Gujarat", region: "West" },
  { pincode: "395008", city: "Surat", state: "Gujarat", region: "West" },
  { pincode: "395009", city: "Surat", state: "Gujarat", region: "West" },
  { pincode: "395010", city: "Surat", state: "Gujarat", region: "West" },
  { pincode: "395012", city: "Surat", state: "Gujarat", region: "West" },
  // Nagpur
  { pincode: "440001", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440002", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440003", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440006", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440008", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440009", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440010", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440012", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440013", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440014", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440015", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440016", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440017", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440018", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440019", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440022", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440024", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440025", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440027", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440030", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440032", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440033", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440034", city: "Nagpur", state: "Maharashtra", region: "Central" },
  { pincode: "440035", city: "Nagpur", state: "Maharashtra", region: "Central" },
  // Remote / small towns (not deliverable by default)
  { pincode: "334001", city: "Bikaner", state: "Rajasthan", region: "North" },
  { pincode: "334003", city: "Bikaner", state: "Rajasthan", region: "North" },
  { pincode: "334004", city: "Bikaner", state: "Rajasthan", region: "North" },
  { pincode: "345001", city: "Jaisalmer", state: "Rajasthan", region: "North" },
  { pincode: "345023", city: "Jaisalmer", state: "Rajasthan", region: "North" },
  { pincode: "174001", city: "Bilaspur", state: "Himachal Pradesh", region: "North" },
  { pincode: "175001", city: "Mandi", state: "Himachal Pradesh", region: "North" },
  { pincode: "176001", city: "Kangra", state: "Himachal Pradesh", region: "North" },
  { pincode: "176051", city: "Dharamshala", state: "Himachal Pradesh", region: "North" },
  { pincode: "176061", city: "Palampur", state: "Himachal Pradesh", region: "North" },
  { pincode: "171001", city: "Shimla", state: "Himachal Pradesh", region: "North" },
  { pincode: "171002", city: "Shimla", state: "Himachal Pradesh", region: "North" },
  { pincode: "171003", city: "Shimla", state: "Himachal Pradesh", region: "North" },
  { pincode: "171004", city: "Shimla", state: "Himachal Pradesh", region: "North" },
  { pincode: "171005", city: "Shimla", state: "Himachal Pradesh", region: "North" },
  { pincode: "171006", city: "Shimla", state: "Himachal Pradesh", region: "North" },
  { pincode: "171009", city: "Shimla", state: "Himachal Pradesh", region: "North" },
  { pincode: "175101", city: "Kullu", state: "Himachal Pradesh", region: "North" },
  { pincode: "175131", city: "Manali", state: "Himachal Pradesh", region: "North" },
  { pincode: "793001", city: "Shillong", state: "Meghalaya", region: "Northeast" },
  { pincode: "793003", city: "Shillong", state: "Meghalaya", region: "Northeast" },
  { pincode: "793005", city: "Shillong", state: "Meghalaya", region: "Northeast" },
  { pincode: "781001", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781003", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781005", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781006", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781007", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781008", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781009", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781010", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781011", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781014", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781016", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781018", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781020", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781022", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781024", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781028", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781029", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781032", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781034", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781035", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781036", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781037", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781038", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781039", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "781040", city: "Guwahati", state: "Assam", region: "Northeast" },
  { pincode: "795001", city: "Imphal", state: "Manipur", region: "Northeast" },
  { pincode: "796001", city: "Aizawl", state: "Mizoram", region: "Northeast" },
  { pincode: "797001", city: "Kohima", state: "Nagaland", region: "Northeast" },
  { pincode: "799001", city: "Agartala", state: "Tripura", region: "Northeast" },
  { pincode: "790001", city: "Itanagar", state: "Arunachal Pradesh", region: "Northeast" },
  { pincode: "737101", city: "Gangtok", state: "Sikkim", region: "Northeast" },
];

export function lookupPincode(pincode: string): PincodeInfo | undefined {
  return PINCODE_DATABASE.find((p) => p.pincode === pincode);
}

export function searchPincodes(query: string): PincodeInfo[] {
  const lower = query.toLowerCase();
  return PINCODE_DATABASE.filter(
    (p) =>
      p.pincode.includes(lower) ||
      p.city.toLowerCase().includes(lower) ||
      p.state.toLowerCase().includes(lower)
  );
}

// Major metro area pincodes - these are "always deliverable"
const METRO_PREFIXES = ["1100", "4000", "5600", "6000", "7000", "5000", "1220", "2013"];

// Tier-2 city prefixes - "usually deliverable"  
const TIER2_PREFIXES = ["3020", "3800", "4110", "2260", "1600", "4520", "4620", "3950", "4400", "8000", "6820"];

export function isMetroArea(pincode: string): boolean {
  return METRO_PREFIXES.some((prefix) => pincode.startsWith(prefix));
}

export function isTier2Area(pincode: string): boolean {
  return TIER2_PREFIXES.some((prefix) => pincode.startsWith(prefix));
}
